[package]
name = "finder-files-organizer"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.9"

[[bin]]
name = "finder-files-organizer"
path = "src/main.rs"
